<!-- Start WOWSlider.com BODY section --> <!-- add to the <body> of your page -->
<link rel="stylesheet" type="text/css" href="{$smarty.const.ROOTURL}assets/modules/my_slide/css/style.css" />
<style>
#wowslider-container1 .ws_bullets a {
	background-image: url({$smarty.const.ROOTURL}assets/modules/my_slide/img/bullet.png);
}
#wowslider-container1 a.ws_next, #wowslider-container1 a.ws_prev {
	background-image: url({$smarty.const.ROOTURL}assets/modules/my_slide/img/arrows.png);
}
</style>
<div id="wowslider-container1">
<div class="ws_images"><ul>
  <li><a href="http://wowslider.com/vi"><img src="{$smarty.const.ROOTURL}_sandboxs/my_box/headslide/home1.jpg" alt="slider" title="home1" id="wows1_0"/></a></li>
  <li><img src="{$smarty.const.ROOTURL}_sandboxs/my_box/headslide/information1.jpg" alt="information1" title="information1" id="wows1_1"/></li>
</ul></div>
<div class="ws_bullets"><div>
  <a href="#" title="home1"><span>1</span></a>
  <a href="#" title="information1"><span>2</span></a>
</div></div><div class="ws_script" style="position:absolute;left:-99%"><a href="http://wowslider.com">wowslideshow</a> by WOWSlider.com v8.7</div>
<div class="ws_shadow"></div>
</div>
<script type="text/javascript" src="{$smarty.const.ROOTURL}assets/modules/my_slide/js/wowslider.js"></script>
<script type="text/javascript">
  // -----------------------------------------------------------------------------------
  // http://wowslider.com/
  // JavaScript Wow Slider is a free software that helps you easily generate delicious
  // slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
  // Generated by WOW Slider 8.7
  //
  //***********************************************
  // Obfuscated by Javascript Obfuscator
  // http://javascript-source.com
  //***********************************************
  jQuery("#wowslider-container1").wowSlider({
    effect: "shift,louvers,parallax,basic_linear",
    prev: "",
    next: "",
    duration: 20 * 100,
    delay: 20 * 100,
    width: 1420,
    height: 463,
    autoPlay: true,
    autoPlayVideo: false,
    playPause: false,
    stopOnHover: true,
    loop: false,
    bullets: 1,
    caption: false,
    captionEffect: "parallax",
    controls: true,
    controlsThumb: false,
    responsive: 2,
    fullScreen: false,
    gestures: 2,
    onBeforeStep: 0,
    images: 0
  });
</script>
